#!/bin/bash

function checkservice() {

case "$(/bin/systemctl -n1 status $1 2>&1)" in
    *"Loaded: not-found"*)
        echo "unknown"
        ;;
    *"could not be found"*)
        echo "unknown"
        ;;
    *"Active: inactive"*)
        echo "down!"
        ;;
    *"Active: active"*)
        echo "up"
        ;;
    *)
        echo "(error)"
        ;;
    esac
}

if [ -z "$1" ];
then 
   echo "bad syntax"
else
   echo $(checkservice "$1")
fi
